FROM python:3.7-alpine

# Created the infrastructure after I created the image
# docker exec -it <ps-hash> sh

# mkdir /app
# apk add nano
# cd /app
# nano first.py
# python3 first.py

# exit and verify connection
